# Generated by Django 5.2.5 on 2025-08-14 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("episode_number", models.IntegerField()),
                ("overview", models.TextField(null=True)),
                ("still_path", models.TextField(null=True)),
                ("vote_average", models.FloatField()),
                ("themoviedb_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("overview", models.TextField(null=True)),
                ("poster_path", models.TextField(null=True)),
                ("season_number", models.IntegerField()),
                ("vote_average", models.FloatField()),
                ("themoviedb_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tvshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("number_of_seasons", models.IntegerField()),
                ("number_of_episodes", models.IntegerField()),
                ("origin_country", models.CharField(max_length=255)),
                ("original_language", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("poster_path", models.TextField(null=True)),
                ("overview", models.TextField(null=True)),
                ("themoviedb_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrewMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("original_name", models.TextField()),
                ("profile_path", models.TextField()),
                ("department", models.TextField()),
                ("job", models.TextField()),
                ("themoviedb_id", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episodes",
                    models.ManyToManyField(
                        related_name="crew", to="themoviedb.episode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("character", models.CharField(max_length=255)),
                ("themoviedb_id", models.TextField()),
                ("original_name", models.TextField()),
                ("profile_path", models.TextField()),
                ("known_for_department", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episodes",
                    models.ManyToManyField(
                        related_name="guests", to="themoviedb.episode"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="themoviedb.season",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="tvshow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="themoviedb.tvshow",
            ),
        ),
    ]
