# Generated by Django 5.2.5 on 2025-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("themoviedb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="job",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="original_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="profile_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="crewmember",
            name="themoviedb_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="episode",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="episode",
            name="still_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="themoviedb_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="known_for_department",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="original_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="profile_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="guest",
            name="themoviedb_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="season",
            name="poster_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="themoviedb_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="poster_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tvshow",
            name="themoviedb_id",
            field=models.CharField(max_length=255),
        ),
    ]
