# Generated by Django 5.2.5 on 2025-08-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
